# Generated by Django 2.2.7 on 2019-11-15 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20191115_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tools',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
