# Generated by Django 2.2.7 on 2019-12-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='gif',
            field=models.ImageField(default='NA', upload_to='gifs/'),
        ),
    ]
