# Generated by Django 2.2.7 on 2019-12-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='icons',
            field=models.ImageField(default='NA', upload_to='icons/'),
        ),
    ]
