# Generated by Django 2.2.7 on 2019-12-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_icons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='icons',
            new_name='icon',
        ),
    ]
