# Generated by Django 2.2.7 on 2020-01-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20191230_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='icon',
        ),
    ]
