# Generated by Django 2.2.7 on 2020-01-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_job_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='github',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
